default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("NCG_BLOG_DB_HOST", "localhost") %>
  port: <%= ENV.fetch("NCG_BLOG_DB_PORT", "5432") %>
  username: <%= ENV["NCG_BLOG_DATABASE_USERNAME"] %>
  password: <%= ENV["NCG_BLOG_DATABASE_PASSWORD"] %>

development:
  <<: *default
  database: <%= ENV.fetch("NCG_BLOG_DB_NAME", "ncg_blog_development") %>

test:
  <<: *default
  database: ncg_blog_test

production:
  <<: *default
  database: <%= ENV.fetch("NCG_BLOG_DB_NAME", "ncg_blog_production") %>
